###Get for data from json file as array only
GET http://localhost:7016/src/kSampleFolder/ksSample/BodyCheck

###Get for data from json file as array only
GET http://localhost:7016/src/kSampleFolder/ksSample/RowCount

###Get for data from json file as array only
GET http://localhost:7016/src/kSampleFolder/ksSample/DataOnly

###Get for as is data
GET http://localhost:7016/src/kSampleFolder/ksSample

###Get for data transformed to Modal data
GET http://localhost:7016/src/kSampleFolder/ksSample/FromModal


###Get for data transformed to Modal data and Uuid also
GET http://localhost:7016/src/kSampleFolder/ksSample/FromModalUuid


###Get for data transformed to Modal data , Uuid and timeStamp also
GET http://localhost:7016/src/kSampleFolder/ksSample/FromModalUuidAndTS

###Get for as is data
GET http://localhost:7016/src/kSampleFolder/ksSample/1

###Get Row Count By Key and Value
GET http://localhost:7016/bin/Factory/VoucherDetails/RowCount/VoucherNumber/1