###insert to FindKey in body     Ex: "FindKey":"new Date(e.DateTime).toISOString().split('T')[0]"
###insert to FindValue in body   Ex:"FindValue":"2024-03-05"

POST http://localhost:7016/bin/Transactions/ANR/GetBybody
content-type: application/json

{
"FindKey":"new Date(e.DateTime).toISOString().split('T')[0]",
"FindValue":"2024-03-05"
}