###insert to value a key in root of that row
###insert to value a key in root of that row

POST http://localhost:7016/bin/Transactions/ANR/GetUsingLoadAsh/2
content-type: application/json

{
"FindKey":"ItemsInOrder.2.Pcs"
}